global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager.retriever:9093']

# Rule files
rule_files:
  - /etc/prometheus/alert_rules.yml

# Scrape configurations
scrape_configs:
  - job_name: 'jaeger-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['collector_prometheus_scrape.retriever:8889']  # Scrape metrics from Jaeger collector's Prometheus endpoint
## the targets value had to be renamed to match the collector_prometheus_scrape in collector.tf 
## previous version of connector would not work since there was no DNS entry for that namespace. 